pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages
  {
        stage('Checkout SCM') {
            steps {
                git(
                    url: 'https://github.com/Vinodhnv-reddy/Abhishek_veeramalla_Jenkins_tutorial.git',
                    credentialsId: 'Vinodhnv-reddy', // add your credentials ID here
                    branch: 'main' // or your desired branch
                )
            }
  {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
  }
}
